python format_data.py ../../datasets/haberman.formatted.data.50.train ../datasets/haberman.50.train  0
python format_data.py ../../datasets/haberman.formatted.data.50.test ../datasets/haberman.50.test  0
python format_data.py ../../datasets/haberman.formatted.data.60.train ../datasets/haberman.60.train  0
python format_data.py ../../datasets/haberman.formatted.data.60.test ../datasets/haberman.60.test  0
python format_data.py ../../datasets/haberman.formatted.data.70.train ../datasets/haberman.70.train  0
python format_data.py ../../datasets/haberman.formatted.data.70.test ../datasets/haberman.70.test  0
python format_data.py ../../datasets/haberman.formatted.data.80.train ../datasets/haberman.80.train  0
python format_data.py ../../datasets/haberman.formatted.data.80.test ../datasets/haberman.80.test  0
python format_data.py ../../datasets/haberman.formatted.data.90.train ../datasets/haberman.90.train  0
python format_data.py ../../datasets/haberman.formatted.data.90.test ../datasets/haberman.90.test  0
python format_data.py ../../datasets/iris-number-classes.data.50.train ../datasets/iris.50.train  0
python format_data.py ../../datasets/iris-number-classes.data.50.test ../datasets/iris.50.test  0
python format_data.py ../../datasets/iris-number-classes.data.60.train ../datasets/iris.60.train  0
python format_data.py ../../datasets/iris-number-classes.data.60.test ../datasets/iris.60.test  0
python format_data.py ../../datasets/iris-number-classes.data.70.train ../datasets/iris.70.train  0
python format_data.py ../../datasets/iris-number-classes.data.70.test ../datasets/iris.70.test  0
python format_data.py ../../datasets/iris-number-classes.data.80.train ../datasets/iris.80.train  0
python format_data.py ../../datasets/iris-number-classes.data.80.test ../datasets/iris.80.test  0
python format_data.py ../../datasets/iris-number-classes.data.90.train ../datasets/iris.90.train  0
python format_data.py ../../datasets/iris-number-classes.data.90.test ../datasets/iris.90.test  0
python format_data.py ../../datasets/survey.data.50.train ../datasets/survey.50.train  0
python format_data.py ../../datasets/survey.data.50.test ../datasets/survey.50.test  0
python format_data.py ../../datasets/survey.data.60.train ../datasets/survey.60.train  0
python format_data.py ../../datasets/survey.data.60.test ../datasets/survey.60.test  0
python format_data.py ../../datasets/survey.data.70.train ../datasets/survey.70.train  0
python format_data.py ../../datasets/survey.data.70.test ../datasets/survey.70.test  0
python format_data.py ../../datasets/survey.data.80.train ../datasets/survey.80.train  0
python format_data.py ../../datasets/survey.data.80.test ../datasets/survey.80.test  0
python format_data.py ../../datasets/survey.data.90.train ../datasets/survey.90.train  0
python format_data.py ../../datasets/survey.data.90.test ../datasets/survey.90.test  0
python format_data.py ../../datasets/wine.data.50.train ../datasets/wine.50.train  0
python format_data.py ../../datasets/wine.data.50.test ../datasets/wine.50.test  0
python format_data.py ../../datasets/wine.data.60.train ../datasets/wine.60.train  0
python format_data.py ../../datasets/wine.data.60.test ../datasets/wine.60.test  0
python format_data.py ../../datasets/wine.data.70.train ../datasets/wine.70.train  0
python format_data.py ../../datasets/wine.data.70.test ../datasets/wine.70.test  0
python format_data.py ../../datasets/wine.data.80.train ../datasets/wine.80.train  0
python format_data.py ../../datasets/wine.data.80.test ../datasets/wine.80.test  0
python format_data.py ../../datasets/wine.data.90.train ../datasets/wine.90.train  0
python format_data.py ../../datasets/wine.data.90.test ../datasets/wine.90.test  0